/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConnectGoogleRouteImport } from './routes/admin/connect-google'
import { Route as ApiPublicBookingsRouteImport } from './routes/api/public/bookings'
import { Route as ApiGoogleConnectRouteImport } from './routes/api/google/connect'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnectGoogleRoute = AdminConnectGoogleRouteImport.update({
  id: '/admin/connect-google',
  path: '/admin/connect-google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingsRoute = ApiPublicBookingsRouteImport.update({
  id: '/api/public/bookings',
  path: '/api/public/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConnectRoute = ApiGoogleConnectRouteImport.update({
  id: '/api/google/connect',
  path: '/api/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/connect-google': typeof AdminConnectGoogleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/connect-google': typeof AdminConnectGoogleRoute
  '/admin': typeof AdminIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/connect-google': typeof AdminConnectGoogleRoute
  '/admin/': typeof AdminIndexRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/public/bookings': typeof ApiPublicBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin/connect-google'
    | '/admin/'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/public/bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin/connect-google'
    | '/admin'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/public/bookings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/privacy'
    | '/terms'
    | '/admin/connect-google'
    | '/admin/'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/public/bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminConnectGoogleRoute: typeof AdminConnectGoogleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleConnectRoute: typeof ApiGoogleConnectRoute
  ApiPublicBookingsRoute: typeof ApiPublicBookingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connect-google': {
      id: '/admin/connect-google'
      path: '/admin/connect-google'
      fullPath: '/admin/connect-google'
      preLoaderRoute: typeof AdminConnectGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bookings': {
      id: '/api/public/bookings'
      path: '/api/public/bookings'
      fullPath: '/api/public/bookings'
      preLoaderRoute: typeof ApiPublicBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/connect': {
      id: '/api/google/connect'
      path: '/api/google/connect'
      fullPath: '/api/google/connect'
      preLoaderRoute: typeof ApiGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminConnectGoogleRoute: AdminConnectGoogleRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleConnectRoute: ApiGoogleConnectRoute,
  ApiPublicBookingsRoute: ApiPublicBookingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
